### ISSUE TITLE
feature: [파트너스] 회원 가입

### ISSUE THREAD

**Issue by good4y** [129cm/backend-api#1]
## 기능 설명

> 설명을 작성해 주세요

파트너스의 회원 가입 기능을 작성한다.

## TO-DO
- [x] API 문서에 맞춰 Brand, Partners Entity 클래스를 만든다.
- [x] Partners 회원가입 시 작성한 Brand가 생성되어야 한다.
- [ ] email 유효성 검사를 수행한다.
- [ ] 비밀번호는 8자리 이상, 알파벳 대소문자, 일반적으로 허용되는 문자 하나 이상을 포함해야 한다.
- [x] 테스트 코드를 작성한다.

## 참고 사항

> 참고 사항을 작성해 주세요
