### ISSUE TITLE
feature: [회원] 브랜드 조회

### ISSUE THREAD

**Issue by kuma0112** [129cm/backend-api#24]
## 기능 설명

> 설명을 작성해 주세요

129cm 이용자의 브랜드 조회 기능을 작성한다.

## TO-DO
- [ ] 정렬 기준은 최신순, 낮은가격순, 판매순이 있으며, 기본 정렬 기준은 최신순이다. 
- [ ] 정렬 순서는 오름차순, 내림차순이 있으며, 기본 정렬 순서는 내림차순이다. 
- [ ] 회원 브랜드 조회 기능의 테스트 코드를 작성한다. 

## 참고 사항

> 참고 사항을 작성해 주세요
