### ISSUE TITLE
feature: [회원] 회원 가입

### ISSUE THREAD

**Issue by good4y** [129cm/backend-api#4]
## 기능 설명

> 설명을 작성해 주세요

129cm 이용자의 회원 가입 기능을 작성한다.

## TO-DO
- [ ] 회원 엔티티를 작성한다.
- [ ] 이메일 검사를 수행한다.
- [ ] 비밀번호는 8자리 이상, 20자리 이하 그리고 영문 대소문자, 문자 하나 이상을 포함한다.

## 참고 사항

> 참고 사항을 작성해 주세요
